spring:
#  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      repositories:
#        enabled: true
#      cluster-nodes: 192.168.150.131:9300
  es:
    host: 192.168.150.131
    port: 9300