spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      repositories:
        enabled: true
      cluster-nodes: 106.12.84.126:9300
  elasticsearch:
    rest:
      uris: http://106.12.84.126:9200