spring:
  application:
    name: itcast-dubbo-service
server:
  port: 9090
dubbo:
  service:
    version: 1.0.0
  scan:
    base-packages: cn.itcast.dubbo.service
  application:
    name: dubbo-provider-demo
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.150.131:2181
    client: zkclient