spring:
  application:
    name: feign-api
server:
  port: 9003
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
feign:
  hystrix:
    enabled: true
ribbon:
  eager-load:
    enabled: true