
server:
  port: 9011
qiniu:
  accessKey: 9fQrwFrDdsBowPaNFwmZs8g1H7RLOYwL9cabDx6k
  secretKey: MJECg5MkxW2rp4bVWjCKFJ9dDczkSVnURfYe6JvN
  bucket-name: haoke-huadong
  cdn-prefix: pw0lsxiue.bkt.clouddn.com
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.application.name}
spring:
  application:
    name: qiniu-service
  servlet:
    multipart:
      enabled: true
