spring:
  application:
    name: haoke-zuul
server:
  port: 9002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
  routes:
    house-service:
      path: /uac/**
      serviceId: house-service
      sensitiveHeader:
  ribbon:
    eager-load:
      enabled: true