spring:
  application:
    name: haoke-zuul
server:
  port: 9002
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
  ratelimit:
    key-prefix: your-prefix
    enabled: true
    repository: redis
    behind-proxy: true
    add-response-headers: true
    default-policy-list: #默认的全局配置
      - limit: 10  #每个刷新间隔窗口的请求数量限制
        quota: 1000  #每个刷新间隔窗口的请求时间限制(以秒为单位)
        refresh-interval: 60 #默认值 以秒为单位
        type:
          - user
          - origin
          - url
          - httpmethod
    policy-list: #单个服务配置
      myServiceId:
        - limit: 10 #optional - request number limit per refresh interval window
          quota: 1000 #optional - request time limit per refresh interval window (in seconds)
          refresh-interval: 60 #default value (in seconds)
          type: #optional
            - user
            - origin
            - url
        - type: #optional value for each type
            - user=anonymous
            - origin=somemachine.com
            - url=/api #url prefix
            - role=user
            - httpmethod=get #case insensitive
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Methods #解决跨域获取不到返回值问题
  routes:
    house-service:
      path: /house/**
      serviceId: house-service
      sensitiveHeader:
    feign-api:
      path: /api/**
      serviceId: feign-api
      sensitiveHeader:
    qiniu-service:
      path: /**
      serviceId: qiniu-service
      sensitiveHeader:
  ribbon:
    eager-load:
      enabled: true
      clients: houser-service
    ReadTimeout: 300000
    SocketTimeout: 300000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          #一个容器实例,单个请求超时5S +重试>10s,超15S则熔断
          timeoutInMillseconds: 15000